language: python
sudo: required
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
env:
  - TZ=Europe/Kiev
cache:
  directories:
    - eggs
install:
  - sh bootstrap.sh
script:
  - bin/nosetests
after_success:
  - bin/coveralls

